---
languageCode: "en-AU"
title: "This Week in Technology"
baseURL: "https://www.thisweekin.technology/"
enableRobotsTXT: true
enableGitInfo: true

permalinks:
  issue: "issue/:slug/"

params:
  short_title: 'This Week in Tech'
  github: 'jloh/thisweekintechnology'
  twitter:
    username: "itsjloh"
  medium:
    username: 'twit'
  dateform: "January 2 2006"
  dateformfull: "Monday January 2nd 2006 15:04:05 MST"
  dateformlist: "January 02"
  latestpostcount: 5
  description: "Weekly newsletters about anything technology"
  copyright: 'made with <i class="fa fa-heart" aria-hidden="true"></i> by [jloh](https://jloh.co) and powered by [sendy](http://sendy.co/?ref=XR4yq) and [Netlify](https://www.netlify.com/)'
  logofile: "img/logo.png"
  highlightjs: false
  progressively: false
  latestpostcount: 5
  email: "contact@thisweekin.technology"
  social_banner: "img/banner.png"
  nav_logo: 'img/logo.png'
  posts_navigation: true
  extracssfiles:
   - '/css/custom.css'
  navigation:
    - title: 'Archive'
      url:   '/issues/'
  # - title: 'About'
  #    url:   '/about/'
    - title: 'Sign Up'
      url:   '/#signup'
