---
languageCode: "en-AU"
title: "Byte by Byte"
baseURL: "https://www.bytebybyte.io"
enableRobotsTXT: true
enableGitInfo: true
googleAnalytics: 'UA-98328870-1'

permalinks:
  issue: "issue/:slug/"

params:
  author: 'James Loh'
  AuthorName: 'James Loh'
  github: 'jloh/bytebybyte'
  twitter:
    username: "itsjloh"
  medium:
    username: 'twit'
  dateform: "January 2 2006"
  dateformfull: "Monday January 2nd 2006 15:04:05 MST"
  dateformlist: "January 02"
  latestpostcount: 5
  description: "A weekly newsletter about anything technology"
  copyright: 'Copyright Â© James Loh (Byte by Byte) 2017'
  logofile: "img/logo.png"
  highlightjs: false
  progressively: false
  latestpostcount: 5
  email: "james@bytebybyte.io"
  meta_img: "img/logo.png"
  nav_logo: 'img/logo.png'
  posts_navigation: true
  navigation:
    - title: 'Archive'
      url:   '/issues/'
  # - title: 'About'
  #    url:   '/about/'
    - title: 'Sign Up'
      url:   '/#signup'
