[context.production.environment]
  HUGO_VERSION = "0.38.1"
  HUGO_ENV     = "production"

[context.deploy-preview]
  command = "gulp && hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.38.1"
